### ISSUE TITLE
can you share link to data pls

### ISSUE THREAD

**Issue by Sandy4321** [mohannishant6/Detecting-Frauds-in-Healthcare#1]
great code thanks
can you share link to data pls

as you use
df=pd.read_csv('provider.csv')

**Comment by mohannishant6** [comment]
https://data.cms.gov/Medicare-Part-D/Medicare-Provider-Utilization-and-Payment-Data-Par/psut-35i4

**Comment by Sandy4321** [comment]
great thanks for soon answer, by the way how to find more fraud data with big files size?
